import { StyleSheet } from 'react-native';

export default   StyleSheet.create({
    container:{
        flex:1,
        width:'100%',
        height:'100%',
    },
    bgColorBlue:{
        backgroundColor:'#242c62',
    },
    bgColorYellow:{
        backgroundColor:'#f6d147',
    },
    img:{
        alignSelf:'center',
        resizeMode:'cover',
        width:300,
        height:50,
    },
    h1:{
        fontSize:26,
        color:'#242c62'
    },
    h2:{
        fontSize:20,
        color:'#242c62'
    },
    h3:{
        fontSize:18
    },
    marginTop:{
        marginTop:15
    },
    paddingContainer:{
        padding:15
    },
    indicator:
    {flex:1,alignSelf:'center',justifyContent:'center',alignContent:'center'},
    fontFamily:{
        fontFamily:"Raleway-Light",
    },


    headerContainer:{
        width:'100%',
        flexDirection:'row',
        alignContent:'center',
        justifyContent:'center',
        alignSelf:'center',
        height:50,
        backgroundColor:'#242c62',
    },
    headerText:{
        color:'white'
    },
    iconHeaderLeft:{
        position:'absolute',
        left:0,
        alignSelf:'center',
    },
    iconHeaderRight:{
        position:'absolute',
        right:0,
        alignSelf:'center'
    },
    SideMenu:{
        backgroundColor:'#242c62',
        paddingTop:40,
        paddingBottom:10,
        flex:1,
    },
    headerTitleContainer:{
        
        justifyContent:'center',
        alignItems:'center'
    },
    headerTitleText:{
        color:'white',
        fontSize:16,
    },
    subHeader:{backgroundColor:'transparent',elevation:0,margin:0,paddingLeft:0,alignItems:'center'},
    badgeText:{
        backgroundColor:'#d7385e',
        padding:2,
        borderRadius:18,
        textAlign:'center',
        color:'white',
        marginLeft:3,
        fontSize:13
    }
})