import { StyleSheet } from 'react-native';

export default  StyleSheet.create({
    logoMenu:{
        marginTop:20,
        marginBottom:20
    },
    sideScroll:{
            flex:1,
            height:'100%'
    },
    bigTitle:{
        color:'white',
        fontSize:20,
        width:'100%',
        backgroundColor:'#f6d147',
        paddingTop:10,
        paddingBottom:10,
        paddingLeft:10,
        alignSelf:'center'
    },
    ItemMenu:{
        flexDirection:'row',
        alignItems:'center',
        paddingTop:10,
        paddingBottom:10,
        paddingLeft:16,
    },
    ItemTextMenu:{
        color:'white',
        letterSpacing:1,
        marginLeft:8,
        alignSelf:'center',
        fontSize:16,
        letterSpacing:0.5,
    },
    groupMenu:{
        marginBottom:6
    }
})