<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBRh3QzG\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBRh3QzG/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBRh3QzG.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBRh3QzG\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBRh3QzG\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BRh3QzG',
    'container.build_id' => '7a8a18b5',
    'container.build_time' => 1603263691,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBRh3QzG');
