<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIOh6cG1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIOh6cG1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIOh6cG1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIOh6cG1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIOh6cG1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IOh6cG1',
    'container.build_id' => 'fd842921',
    'container.build_time' => 1602262841,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIOh6cG1');
