<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOaxBheX\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOaxBheX/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOaxBheX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOaxBheX\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOaxBheX\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OaxBheX',
    'container.build_id' => 'c65bf5fe',
    'container.build_time' => 1602131273,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOaxBheX');
